### ISSUE TITLE
compiling on taub (see notes)

### ISSUE THREAD

**Issue by jdsteve2** [shigh/pswr-charm#10]
I'm stuck, but here's what I figured out so far...
1. of course you need to make sure CHARMC is set
2. you also need to do "module load petsc" (this sets PETSC_DIR but not PETSC_ARCH, this might be a problem....)
3. after doing this, it compiles the swr.ci file, but then doesn't recognize "--std=c++11" so you have to do "module load gcc"
4. now it understands "--std=c++11" but it can't find mpi.h, I haven't gotten past this yet

I've messed around with this for a while without success.

**Comment by shigh** [comment]
I got it to build and finish 'make test' and 'make test-swr', see branch taub.

Do not use the petsc on taub. Run this script to install petsc before you load any modules. I built it in ~/src.

``` bash
#!/bin/bash --login

# Unset petsc env variables
# The build will fail if they are already set to a different
# directory
unset PETSC_DIR
unset PETSC_ARCH

# Download petsc and unpack
wget http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.5.2.tar.gz
tar xzf petsc-3.5.2.tar.gz

# configure and build
cd petsc-3.5.2
./configure --with-cc=gcc --with-cxx=g++ --with-fc=gfortran --with-mpi=0
make all test
```

I had to adjust the Makefile to include the correct mpi.h, the one that petsc compiles with when you are not running with mpi. I think we should use this setup anyways since we are not using mpi.

I also needed to set LD_LIBRARY_PATH for this to work. My setup.sh script for taub is:

``` bash
#!/bin/bash --login

module load gcc

export PETSC_DIR=~/src/petsc-3.5.2
export PETSC_ARCH=arch-linux2-c-debug
export LD_LIBRARY_PATH=${PETSC_DIR}/${PETSC_ARCH}/lib:$LD_LIBRARY_PATH

export CHARMC=~/src/charm/net-linux-x86_64/bin/charmc
```

If you built everything in ~/src you can use this without modification.

**Comment by shigh** [comment]
I rebuilt petsc on my desktop using the above script and ran with the updated Makefile, all of test cases pass.

I think my above comment would be a good thing to put in a wiki page...

**Comment by shigh** [comment]
@pranjalv123 @jdsteve2 , does this work for you? If so we can close this issue.

**Comment by jdsteve2** [comment]
I can make and run locally... thanks!
(on taub)
